# Spring
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
# Springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true
# Application
application:
  security:
    jwt:
      refresh-expiration: 30
      expiration: 15
      key: This key MUST have a size >= 256 bits or else a WeakKeyException will be thrown.
